### ISSUE TITLE
RPG-Skilltext.rb

### ISSUE THREAD

**Issue by charrednewth** [Freeloader-Zero/Succubus-Rhapsodia-ENG#5]
Hi! No really an issue since it'll be easy to fix, but it might save you a little work (this one is an example):

```
 case $data_SDB[target.class_id].name
  when "Lesser Succubus ","Succubus", "Vermiena"
    tail = "flexible tail"
  when "Iｍp","Devil ","Deｍon", "Yuganaught"
    tail = "spaded tail"
  when "Werecat ","Werewolf","Taｍaｍo"
    tail = "fluffy tail"
  when "Fulbeua ", "Neijorange", "Succubus Lord "
    tail = "glossy tail"
  when "Familiar", "Rejeo ", "Sylphe"
    tail = "delicate tail"
  when "Gargoyle"
    tail = "squarish tail"
  else
    tail = "tail"
  end
```

Replacing anything in the when "..." lines is unnecessary, because it will require us to add another file to the patch (classes.rxdata here). It's not really useful, and will require us to look for other instances of $data_SDB[target.class_id].name  if we, indeed, change classes.rxdata directly. (it's $data_SDB here, not the original classes.rxdata, I'm still unsure whether to edit it directly, or stick with the easy translation_check)
In any case, the "text = ..." (tail =, in that case) line is more than enough. 

Well, it's no biggie, and I'm sure you already knew.

Good job so far btw!

I've uploaded the items database on my side, I'm about 60% satisfied since I've end up taking many liberties with some names/descriptions (hoping to stick with the original 'feel'). But it's workable and easy to edit. No need to look its way until the polishing phase, I hope.
Only remarks:
- still clueless about item#3, the 滞在機の鍵
- I went with 'Pelfrey' for the magical order's roman name, for now.

I'l let you know when I've solved the conflicts with some names between our versions (I'll stick to your names in 98% cases). Everything I've done so far is non-intrusive, and 'only' adds a database which can easily be accessed via UK_name or UK_description.  In other words, once I'm done cross-checking, you should be able to integrate it in your SR version without any of my lines disrupting your work in any way... Hopefully :)

'later!

**Comment by Freeloader-Zero** [comment]
Well, shit... I'm clueless as well about item 3 (滞在機の鍵)... best guess is something to do with the Home, but let's leave it as is for now until either of us find it in game or in whatever map/common event that gives it and/or what event uses it. Need context xD...

Anyways, I 'm super excited about things are looking on your end! Especially those skill descriptions (gah it took forever to check through the skills.rxdata and copy/paste every time the dev changed the file; lol). I'm currently in the process of integrating your scripts, but I came up against an issue - I can't seem to get  most of your translations to work (e.g. items, skill descriptions, personalities); are they working on your end, or are they still a work in progress? :x I only copied over your scripts 003 through 007; could I be missing something?

**Comment by charrednewth** [comment]
Bad news on my side: while doing a last-minute check yesterday I wanted to compare with 1.10, so I've reapplied the patch WITH scripts.rxdata, in the RONG folder... 4-6 hours lost. I am so, very, very glad you've created this Github... Otherwise I'd have lost much more. 

Brighter news:
- I still haven't killed myself for being so stupid. Call it lazyness.
- I'll make a simple commit with the items display as an example. 100% sure that'll work on a vanilla copy. I don't have your entire, exact script copy on a working version, so there might be conflicts with your own work - let me know, can't be too hard. I'll ask you to upload your own scripts.rxdata if it's anything that needs intricate tinkering.
- skills, etc might be trickier. Let me know where/when you want them to show (battle? Menu? Box?) and I'll test wether it's OK before I commit the script for you.
- enemies are more complicated, since some "battlers" are created for the battle only. I'll have to double-check here, but I think my def's were enough - I might be wrong

**Comment by charrednewth** [comment]
Done for Window_Item. CTRL-F for "UK_" will show you the 2 changes I made to original file. 
Simple as that; that covers the items in the menu->items display. (there are still TODOs in the database itself)

You'll need some other part like "Window_EquipItem" for the equiping part. But I made it so it is easy to implement / withdraw the English bits - given the database is complete.

**Comment by Freeloader-Zero** [comment]
Lol I've done that twice already - edited the original copy that was meant to be left clean rather than my own copy xD.

My Scripts.rxdata is in the Data github folder. You can also get it via the links on the ULMF OP. However as long as your own translations are working for you, I'll look at them and do the merging. I need to look through them regardless; I'll note what I change or keep from which copy (yours, mine, or even the vanilla in some cases) when I merge.

Now I haven't looked at your most recent changes, but for skills, the only instance I've found where your skill proxy method didn't work was the little announcer message at the top of the screen when battling. Every other instance translated perfectly (menus). 

For enemies, I've stuck with my invasive replacement methods of the database (rxdata) names because the party menu pulls the names from Classes.rxdata while the enemy names come from Enemies.rxdata; I couldn't figure out how to get the scripts to draw based on your toolbox. Replacing the actor.name instances with actor.UK_name didn't work for me.

Your traits/abilities work great, I remember even the descriptions showed while using Check on bosses.

Anyways, I'll check out your translations a little later after eating and sorting some of my own translations. :)

**Comment by charrednewth** [comment]
For enemies: Patches 2 and 4 should do the trick. I forgot these lines had to go where initialization takes place.

Patch 3 is the clean Game_Enemy script  (file 42?). I'm unsure you can use it to compare, though...

And, sure. I'm a quality nazi too, I've told you :p You're much better than me for writing/translating anyway, from what I've seen already.

Cya!

**Comment by Freeloader-Zero** [comment]
Your Items translations work perfectly now - ahh glorious English! xD

However, the skill descriptions and enemy names still don't work on my end, having tried them both on a fresh copy and my personal copy; do they work on your end?

Just to be sure, these are the sections I've implemented from either your scripts (including from patch 2 and 4) or with me manually replacing .name with .UK_name:
- Translation check / Toolbox
- Enemies, classes, people
- Skills English
- States English
- Items&equip English
- RPG::Ability（素質・設定用）
- Game_Battler 1
- Game_Enemy
- Window_Item
- Window_Skill
- Window_Skill_Battle
- Window_EquipItem

Am I missing something? :x 

p.s. I'll be out of town for a week; will be slower with progress and replies, but I'll still be around. :)

**Comment by Freeloader-Zero** [comment]
p.s. had to comment out lines to 106-112 in "Enemies, classes, people". The "class Game_Actor < Game_Battler" was making it so that the skilltext and statetext messages would either default to the one that was triggered by "else" (when no conditions were met, in the case of skilltext) or they wouldn't play at all (in the case of statetext).

**Comment by charrednewth** [comment]
I'll have to update this... I've commited the battlers definitions for UK_name AND UK_class_name, they should be usable. Let me know if I forgot anything else - they work like a charm for me but I might have forgotten something else.

I'll try and post my fav' setup for menu in ULMF. As you said, it's mostly aesthetics, but hey...

Real life is catching up on my side, so I might be around less these days as well.

**Comment by Freeloader-Zero** [comment]
Yeah, the latest of your scripts don't seem to work; there's probably stuff that's not been accounted for in the extracted scripts.

Could you push/upload a working version of the scripts.rxdata? I'll get a more complete understanding that way.

**Comment by charrednewth** [comment]
Sure! Everything works fine on my side, but I've been adding/modifying left and right without a decent changelog, so...
I haven't done much for a week (GUIs/windows are pretty much 90% English though), but I'll get that up this w-e. I haven't fully implemented your lines, nor the talk folder content. I can upload what I have right now, if you need it. Only issues I have for now, are with the additional/verbose dialogues.

**Comment by Freeloader-Zero** [comment]
Yeah I'll be leaving out Mimi's talk folder integration until I can properly test what's going on. Go ahead and upload what you have, I'll manually compare our versions.

Also, by "additional/verbose dialogues", do you mean the stuff in the talk folder? If not, what script section seems to be the problem?

**Comment by charrednewth** [comment]
Here:https://github.com/charrednewth/Succubus-Rhapsodia-ENG/blob/master/Data/Scripts%20-%20WIP.rxdata

However, I'm missing much of what I had previously done with the earlier version. This is very incomplete, for now at least. I'm hoping to get some work done here before Monday.

Let me know if something went wrong - this should be very stable.
